---
services:
  mddo-clab-docker:
    container_name: mddo-clab-docker
    privileged: true
    pid: "host"
    network_mode: "host"
    restart: on-failure
    image: ghcr.io/ool-mddo/mddo-clab-docker:main
    working_dir: ${WORKERDIR}/clab
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /var/run/netns
        target: /var/run/netns
      - type: bind
        source: /etc/hosts
        target: /etc/hosts
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
      - type: bind
        source: ./ansible-eda
        target: /eda
      - type: bind
        source:  ${WORKERDIR}/clab
        target:  ${WORKERDIR}/clab
  eda-worker:
    privileged: true
    restart: on-failure
    image: ghcr.io/ool-mddo/mddo-ansible-eda:main
    ports:
      - target: 48090
        published: 48090
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /var/run/netns
        target: /var/run/netns
      - type: bind
        source: /etc/hosts
        target: /etc/hosts
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
      - type: bind
        source: ./ansible-eda
        target: /eda
      - type: bind
        source: ./prom
        target: /prom
      - type: bind
        source: ${WORKERDIR}/clab
        #source: ../clab
        target: /clab
      - type: bind
        source: ./playbooks/
        target: /playbooks
    command: ["ansible-rulebook","-r","/eda/rulebook.yaml","-i","/eda/hosts","-vvvv"]
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
      - "--collector.textfile.directory=/data"
    pid: host
    ports:
      - 9100:9100
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
      - './prom:/data'
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.38.6
    ports:
      - target: 8080
        published: 30080
    volumes:
      - type: bind
        source: /
        target: /rootfs
        read_only: true
      - type: bind
        source: /var/run
        target: /var/run
      - type: bind
        source: /sys
        target: /sys
        read_only: true
      - type: bind
        source: /var/lib/docker/
        target: /var/lib/docker
        read_only: true
        
networks:
  default:
    ipam:
      config:
        - subnet: 172.32.0.0/24        
