---
- name: deploycontainerlab
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 48090

  rules:
    - name: clab deploy
      condition: event.payload.message == "clab"
      action:
        run_playbook:
          name: "/playbooks/containerlab.yaml"
          extra_vars:
            network_name: "{{ event.payload.network_name }}"
            crpd_image: "{{ event.payload.crpd_image }}"
            snapshot_name: "{{ event.payload.snapshot_name }}"
            usecase_name: "{{ event.payload.usecase_name }}"
            with_clab: "true"
            remote_address: "{{ event.payload.remote_address }}"
    - name: setup iperf node
      condition: event.payload.message == "iperf"
      action:
        run_playbook:
          name: "/playbooks/iperf.yaml"
          extra_vars:
            network_name: "{{ event.payload.network_name }}"
            crpd_image: "{{ event.payload.crpd_image }}"
            snapshot_name: "{{ event.payload.snapshot_name }}"
            usecase_name: "{{ event.payload.usecase_name }}"
            with_clab: "true"
            iperf_commands: "{{ event.payload.iperf_commands}}"
            remote_address: "{{ event.payload.remote_address }}"
    - name: clab destory
      condition: event.payload.message == "destroy"
      action:
        run_playbook:
          name: "/playbooks/destroy.yaml"
          extra_vars:
            network_name: "{{ event.payload.network_name }}"
            crpd_image: "{{ event.payload.crpd_image }}"
            snapshot_name: "{{ event.payload.snapshot_name }}"
            usecase_name: "{{ event.payload.usecase_name }}"
            with_clab: "true"
            remote_address: "{{ event.payload.remote_address }}"
    - name: shutdown webhook
      condition: event.payload.message == "shutdown"
      action:
        shutdown:
          delay: 15
          message: "Shutting down"       
