---
- name: deploycontainerlab
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 48090

  rules:
    - name: clab deploy
      condition: event.payload.message == "clab"
      action:
        run_playbook:
          name: "/playbooks/containerlab.yaml"
          extra_vars:
            network_name: "{{ event.payload.network_name }}"
            crpd_image: "{{ event.payload.crpd_image }}"
            endpoint_image: "{{ event.payload.endpoint_image }}"
            snapshot_name: "{{ event.payload.snapshot_name }}"
            usecase_name: "{{ event.payload.usecase_name }}"
            with_clab: "true"
            remote_address: "{{ event.payload.remote_address }}"
    - name: setup iperf node
      condition: event.payload.message == "iperf"
      action:
        run_playbook:
          name: "/playbooks/iperf.yaml"
          extra_vars:
            network_name: "{{ event.payload.network_name }}"
            crpd_image: "{{ event.payload.crpd_image }}"
            snapshot_name: "{{ event.payload.snapshot_name }}"
            usecase_name: "{{ event.payload.usecase_name }}"
            with_clab: "true"
            iperf_commands: "{{ event.payload.iperf_commands}}"
            remote_address: "{{ event.payload.remote_address }}"
    - name: clab destroy
      condition: event.payload.message == "destroy"
      action:
        run_playbook:
          name: "/playbooks/destroy.yaml"
          extra_vars:
            network_name: "{{ event.payload.network_name }}"
            crpd_image: "{{ event.payload.crpd_image }}"
            endpoint_image: "{{ event.payload.endpoint_image }}"
            snapshot_name: "{{ event.payload.snapshot_name }}"
            usecase_name: "{{ event.payload.usecase_name }}"
            with_clab: "true"
            remote_address: "{{ event.payload.remote_address }}"
    - name: shutdown webhook
      condition: event.payload.message == "shutdown"
      action:
        shutdown:
          delay: 15
          message: "Shutting down"
    - name: operate ovs bridge operation(ovs-vsctl add-port/del-port)
      condition: event.payload.message == "ovs"
      action:
        run_playbook:
          name: "/playbooks/ovs.yaml"
          extra_vars:
            network_name: "{{ event.payload.network_name }}"
            snapshot_name: "{{ event.payload.snapshot_name }}"
            usecase_name: "{{ event.payload.usecase_name }}"
            operation: "{{ event.payload.operation }}"
            bridge_name: "{{ event.payload.bridge_name }}"
            port_name: "{{ event.payload.port_name }}"
    - name: vsrx ha deployment
      condition: event.payload.message == "vsrx_ha"
      action:
        run_playbook:
          name: "/playbooks/vsrx_ha.yaml"
          extra_vars:
            cluster_id: "{{ event.payload.cluster_id | default(1) }}"
            password: "{{ event.payload.password | default('password123') }}"
            remote_address: "{{ event.payload.remote_address }}"
            num_if: "{{ event.payload.num_if | default(5) }}"
            node_0_id: "{{ event.payload.node_0_id | default(0) }}"
            node_1_id: "{{ event.payload.node_1_id | default(1) }}"
            node_0_ip: "{{ event.payload.node_0_ip | default('192.168.100.2/24') }}"
            node_1_ip: "{{ event.payload.node_1_ip | default('192.168.100.3/24') }}"
            node_0_if: "{{ event.payload.node_0_if | default('ge-0/0/0') }}"
            node_1_if: "{{ event.payload.node_1_if | default('ge-7/0/0') }}"
