---
### ansible-playbook -i clab-emulated/ansible-inventory.yml show_conf.yml
- name: Collect Junos configuration from vSRX
  hosts: junos # <-- junos グループを対象に指定
  gather_facts: no
  #connection: ansible.netcommon.network_cli
  connection: ansible.netcommon.netconf
  serial: 1

  vars:
    ansible_command_timeout: 120
    ansible_connect_timeout: 120
    ansible_port: 22
    ansible_host_key_checking: false
    ansible_network_os: junipernetworks.junos.junos
    ansible_user: root
    ansible_password: password123
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

  tasks:
    - name: Run show configuration
      junipernetworks.junos.junos_command:
        commands:
          - show configuration
      register: result

    - name: Display configuration
      ansible.builtin.debug:
        msg: "{{ result.stdout[0] }}"
